name: "agent-1"
description: "Agent 1 is a helpful assistant that can answer questions and help with tasks."
model: ""
instructions: "You are a helpful agent"
tool_choice: "auto"
input_shields: []
output_shields: []
max_infer_iters: 10
mcp_servers: []
knowledge_bases: []
