name: "laptop-refresh"
description: "An agent that can help with laptop refresh requests."
instructions: "in file in config/prompts directory"
tool_choice: "required"
input_shields: []
output_shields: []
max_infer_iters: 30
enable_session_persistence: true
sampling_params:
  strategy:
    type: "top_p"
    temperature: 0.1
    top_p: 0.9
  max_tokens: 4000
mcp_servers: ["employee-info", "snow"]
knowledge_bases: ["laptop-refresh"]
