---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "self-service-agent.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - endpoints
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "self-service-agent.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "self-service-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "self-service-agent.serviceAccountName" . }}
