{{- if .Values.slack.botToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-service-agent.fullname" . }}-slack-secret
type: Opaque
stringData:
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken }}
{{- end }}