name: Build and push images

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}    

jobs:
  build-and-push:
    if: github.repository_owner == 'RHEcosystemAppEng'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: self-service-agent
            context: .
          - name: self-service-agent-asset-manager
            context: ./asset-manager
          - name: self-service-agent-employee-info
            context: ./mcp-servers/employee-info
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract version from the GitHub context
        id: version
        run: |
          version=${{ env.BRANCH_NAME }}.${{ github.sha }}
          echo "tag=$version" >> $GITHUB_OUTPUT

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Containerfile
          push: true
          tags: quay.io/ecosystem-appeng/${{ matrix.name }}:${{ steps.version.outputs.tag }}
