name: Pull Request - Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  ASSET_MANAGER_DIR: asset-manager
  # TODO: I tried to define LLM_API_TOKEN as a ${{ secret.LLM_API_TOKEN }}, 
  # but it didn't work for the upstream repo.
  # It only worked for the downstream repo.
  # I spent a lot of time trying to figure out why it didn't work, but I couldn't :(
  LLM_API_TOKEN: d81971fa4ad90db0134fd2a1ce3cd21e
  LLM_URL: https://llama-4-scout-17b-16e-w4a16-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1

jobs:
  pull-request-tests:
    name: Run unit-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.ASSET_MANAGER_DIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ env.ASSET_MANAGER_DIR }}/pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.8.9"

      - name: Install the project
        run: uv sync --extra test
  
      - name: Run tests
        run: uv run pytest tests

  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Validate LLM_API_TOKEN secret
        shell: bash
        env:
          LLM_API_TOKEN: ${{ env.LLM_API_TOKEN }}
        run: |
          if [ -z "${LLM_API_TOKEN}" ]; then
            echo "LLM_API_TOKEN secret is missing or empty. Set it in repository or organization secrets."
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.17"
          python-version: "3.12"

      - name: Install Local Dependencies
        shell: bash
        run: |
          make oc
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Initialize cluster and deploy application
        uses: ./.github/actions/kind
        env:
          LLM_API_TOKEN: ${{ env.LLM_API_TOKEN }}

      - name: Install evaluations dependencies
        run: |
          make sync-evaluations

      - name: Run evaluations
        run: |
          make test-short-integration

      - name: Inspect Cluster - Self-Service Agent
        if: failure()
        uses: ./.github/actions/inspect
        with:
          artifactPrefix: self-service-agent
      